export const FrocksData = [
    {
     id : 1,
      product: 'Frock',
      image: '/Images/F1.jpeg',
      company: 'Flipkart',
      model: 'Casual',
      price: '1500.0',
      rating: 4.5,
      availability: 'In Stock',
    },
    {
      id : 2,
      product: 'Frock',
      image: '/Images/F2.jpeg',
      company: 'Meesho',
      model: 'Partywear',
      price: '2000.0',
      rating: 4.8,
      availability: 'Limited Stock',
    },
    {
      id : 3,
      product: 'Frock',
      image: '/Images/F3.jpeg',
      company: 'Myntra',
      model: 'Formal',
      price: '1800.0',
      rating: 4.6,
      availability: 'In Stock',
    },
    {
      id : 4,
      product: 'Frock',
      image: '/Images/F4.jpeg',
      company: 'Flipkart',
      model: 'Summer Wear',
      price: '1700.0',
      rating: 4.4,
      availability: 'In Stock',
    },
    {
      id : 5,
      product: 'Frock',
      image: '/Images/F5.jpeg',
      company: 'Myntra',
      model: 'Evening Wear',
      price: '2500.0',
      rating: 4.9,
      availability: 'Out of Stock',
    },
    {
      id : 6,
      product: 'Frock',
      image: '/Images/F6.jpeg',
      company: 'Meesho',
      model: 'Casual',
      price: '1600.0',
      rating: 4.3,
      availability: 'In Stock',
    },
  ];